# Unique identifier for the project
sonar.projectKey=sms-project

# Project name
sonar.projectName=Student Management System

# Project version
sonar.projectVersion=1.0.0

# Paths to source directories
sonar.sources=backend/src,frontend

# Language exclusion configs
sonar.exclusions=backend/node_modules/**,backend/tests/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8
